														-- USERS

create table if not exists users (
id int generated by default as identity not null primary key,
name varchar(100) not null,
surname varchar(100) not null,
email varchar(100) not null unique,
birthday date,
number_passport varchar(50) not null unique,
number_driver_license varchar(50),
registration_date date
);

														-- CARS
create table if not exists cars (
id int generated by default as identity not null primary key,
brand varchar(100) not null,
model varchar(100) not null,
year_of_manufacture int not null,
color varchar(100),
document_number varchar(100) not null,
registration_number varchar(10) not null,
owner_id int not null references users(id) on delete cascade on update cascade,
price_per_day int
);

														-- REVIEW
create table if not exists review (
id int generated by default as identity not null primary key,
car_id int not null references cars(id) on delete cascade on update cascade,
user_id int not null,
"text" varchar(1000) not null,
write_date date not null
);

                                                        -- BOOKING
create table if not exists booking (
id int generated by default as identity not null primary key,
user_id int not null references users(id) on delete cascade on update cascade,
car_id int not null references cars(id) on delete cascade on update cascade,
start_rent date not null,
duration int,
booking_status varchar(10),
end_rent date
);

                                                        -- REQUEST_CAR
create table if not exists request_car (
id int generated by default as identity not null primary key,
brand varchar(100),
model varchar(100),
year_of_manufacture varchar(100),
color varchar(100)
);