														-- USERS

create table if not exists users (
id int generated by default as identity not null primary key,
firstname varchar(100) not null,
lastname varchar(100) not null,
email varchar(100) not null unique,
birthday date,
registration_date date
);

														-- CARS
create table if not exists cars (
id int generated by default as identity not null primary key,
brand varchar(100) not null,
model varchar(100) not null,
year_of_manufacture int not null,
color varchar(100),
document_number varchar(100) not null,
registration_number varchar(10) not null,
owner_id int not null references users(id) on delete cascade,
price_per_day int
);

														-- REVIEW
-- нужно единообразие в названиях таблиц. Сейчас в users и cars используется множественное число,
-- а в review, booking и дальше - единственное
create table if not exists review (
id int generated by default as identity not null primary key,
car_id int not null references cars(id) on delete cascade,
user_id int not null references users(id) on delete cascade,
text varchar(5000) not null,
write_date date not null
);

                                                        -- BOOKING
create table if not exists booking (
id int generated by default as identity not null primary key,
user_id int not null references users(id) on delete cascade,
car_id int not null references cars(id) on delete cascade,
start_rent date not null,
duration int not null,
end_rent date not null,
booking_status varchar(10) not null
);

                                                       -- PASSPORT
create table if not exists passport (
id int generated by default as identity not null primary key,
passport_series varchar(4) not null,
passport_number varchar(6) not null,
date_of_issue date not null,
issued_by varchar(500) not null
);

                                                        -- DRIVER_LICENSE
create table if not exists driver_license (
id int generated by default as identity not null primary key,
driver_license_series varchar(5) not null,
driver_license_number varchar(6) not null,
date_of_issue date not null,
issued_by varchar(100) not null
);

